// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosubmitController from "./autosubmit_controller"
application.register("blazer--autosubmit", AutosubmitController)

import BackspaceNavController from "./backspace_nav_controller"
application.register("blazer--backspace-nav", BackspaceNavController)

import CodeExpandController from "./code_expand_controller"
application.register("blazer--code-expand", CodeExpandController)

import DashboardChartController from "./dashboard_chart_controller"
application.register("blazer--dashboard-chart", DashboardChartController)

import DashboardFormController from "./dashboard_form_controller"
application.register("blazer--dashboard-form", DashboardFormController)

import DropdownController from "./dropdown_controller"
application.register("blazer--dropdown", DropdownController)

import HomeSearchController from "./home_search_controller"
application.register("blazer--home-search", HomeSearchController)

import MapController from "./map_controller"
application.register("blazer--map", MapController)

import QueryEditorController from "./query_editor_controller"
application.register("blazer--query-editor", QueryEditorController)

import QueryShowController from "./query_show_controller"
application.register("blazer--query-show", QueryShowController)

import TableFilterController from "./table_filter_controller"
application.register("blazer--table-filter", TableFilterController)

import VariablesFormController from "./variables_form_controller"
application.register("blazer--variables-form", VariablesFormController)
